---
name: Commitlint
on:
  - pull_request
jobs:
  commitlint:
    name: Checking commit message compliance
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
        with:
          fetch-depth: 0
      - run: echo "module.exports = {plugins:['commitlint-plugin-jira-rules'],extends:['jira'],rules:{'jira-task-id-max-length':[2,'always',15],'header-max-length':[2,'always',120]}};" > commitlint.config.js
      - uses: wagoid/commitlint-github-action@296247dfa6a133767fe0d64d08fb66326047b680
